apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "servicemesh.name" . }}-dpl"
  labels:
{{ include "servicemesh.labels" . | indent 4 }}
spec:
{{ if .Values.securityContext }}
  securityContext:
    {{- toYaml .Values.securityContext | nindent 4 }}
{{ end }}
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
{{ include "servicemesh.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "servicemesh.labels" . | indent 8 }}
      annotations:
        kubectl.kubernetes.io/default-logs-container: {{ include "servicemesh.name" . }}
    spec:
      {{- with .Values.podSecurityContext }}
      podSecurityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "servicemesh.name" . }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        lifecycle:
          {{ toYaml .Values.lifecycle | nindent 10 }}