apiVersion: v1
kind: Service
metadata:
  name: "{{ include "servicemesh.name" . }}"
  labels:
{{ include "servicemesh.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.service.port }}
  selector:
{{ include "servicemesh.matchLabels" . | indent 4 }}
{{ if .Values.service.type }}
  type: {{ .Values.service.type }}
{{ end }}